name: Build SukiSU Kernel
on:
  workflow_dispatch:

jobs:
  build:
    # 必须用20.04才能编译这个老内核
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain
        run: |
          sudo apt update
          sudo apt install -y bc bison flex libssl-dev libelf-dev
          sudo apt install -y gcc-aarch64-linux-gnu

      - name: Clone kernel
        run: git clone https://github.com/aHVzY2g/android-kernel-samsung-a22x kernel

      - name: Clone SukiSU
        run: git clone https://github.com/SukiSU-Ultra/SukiSU-Ultra su

      - name: Inject SukiSU
        run: |
          cp -r su/kernel kernel/drivers/su
          cd kernel
          bash drivers/su/setup.sh

      - name: Defconfig
        run: |
          cd kernel
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- O=out a22x_defconfig

      - name: Build
        run: |
          cd kernel
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- O=out -j3 Image.gz-dtb

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Image.gz-dtb
          path: kernel/out/arch/arm64/boot/Image.gz-dtb
